/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controller.ControllerCredenciamento;
import Controller.ControllerInscricao;
import Controller.ControllerPessoa;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author Maycon
 */
public class ConsultaCredenciamento extends javax.swing.JFrame {

    
    private JSONObject jsonRetorno;
    /**
     * Creates new form ConsultaCredenciamento
     */
    public ConsultaCredenciamento() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCredenciamentos = new javax.swing.JTable();
        jComboBoxCampoConsulta = new javax.swing.JComboBox<>();
        jTextFieldValorConsulta = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        DataCredenciamento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Consulta credenciamentos");

        jTableCredenciamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo credenciamento", "Codigo evento", "Descrição evento", "Codigo pessoa", "Nome pessoa", "Data credenciamento"
            }
        ));
        jScrollPane1.setViewportView(jTableCredenciamentos);

        jComboBoxCampoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo pessoa", "Codigo inscricao", "Data credenciamento" }));
        jComboBoxCampoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCampoConsultaActionPerformed(evt);
            }
        });
        jComboBoxCampoConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxCampoConsultaKeyPressed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonConfirmar.setText("Confirmar");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCampoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldValorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(DataCredenciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonBuscar)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jButtonConfirmar)
                        .addGap(72, 72, 72)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxCampoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldValorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBuscar))
                    .addComponent(DataCredenciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonCancelar))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private JSONArray TratamentoComparaData(){                      // A COMPARAÇÃO DE DATAS NAO FUNCIONOU NEM A PORRETE NO BANCO DEPOIS DE HORAS SO CONSEGUI FAZER A COMPARAÇÃO APOS RETORNA DO BANCO O VALOR
            ControllerCredenciamento C = new ControllerCredenciamento(); 
            int dia,mes,ano;
            JSONArray jsonarraytemp = new JSONArray();
            jsonarraytemp = C.RecuperarTodos();
            JSONObject jsonfile = new JSONObject();
            dia = DataCredenciamento.getDate().getDate();
            mes = DataCredenciamento.getDate().getMonth() +1;
            ano = DataCredenciamento.getDate().getYear() +1900;
            String aux = String.valueOf(ano + "-" + mes + "-" + dia);
                       
            for(int i =0; i < jsonarraytemp.size(); i++){
                jsonfile = (JSONObject) jsonarraytemp.get(i);
                
                if(!(aux.equals((jsonfile.get("data").toString())))){
                    //JOptionPane.showMessageDialog(null, jsonarraytemp.size() + aux + "  " + String.valueOf(jsonfile.get("data")));
                    jsonarraytemp.remove(i);
                }
            }       
    
        return jsonarraytemp;
    }
    
    private JSONArray aplicafiltroInscricao(List<Integer> codigosfiltro){
    
        ControllerInscricao I = new ControllerInscricao();
        
        if(codigosfiltro.isEmpty()){
                JOptionPane.showMessageDialog(null, "Registro nao encontrado");
                return null;                                                        // Se nao retornou nada na consulta
            }
            
            String parametros2[][] = new String[codigosfiltro.size()][2];                              // Seta o parametro da coluna que sera consultada chave primaria de pessoas
            //JOptionPane.showMessageDialog(null, codigosfiltro.get(0));
            for(int i = 0; i< codigosfiltro.size(); i++){
                parametros2[i][0] = "pessoa_id";
                parametros2[i][1] = String.valueOf(codigosfiltro.get(i));
            }
        return I.RecuperarPorCodigos(parametros2);
    }
    
    private JSONArray parametrosdeconsulta(){  
        ControllerInscricao I = new ControllerInscricao();
        ControllerPessoa P = new ControllerPessoa();
        ControllerCredenciamento C = new ControllerCredenciamento();
        
        //List<Integer> codigosfiltro;
        JSONArray arrayRetorno = new JSONArray();
 
        String parametros[][] = new String[1][2];   // PRIMEIRO PARAMETRO NOME DA TABELA NO BANCO, SEGUNDO VALOR PARA CONSULTA
         
        
        if(jComboBoxCampoConsulta.getSelectedIndex() == 0){
            parametros[0][0] = "pessoa_id";
            parametros[0][1] = jTextFieldValorConsulta.getText();

            jsonRetorno = P.Recuperar(Integer.valueOf(jTextFieldValorConsulta.getText()));
        }else if(jComboBoxCampoConsulta.getSelectedIndex() == 1){
            parametros[0][0] = "inscricao_id";
            parametros[0][1] = jTextFieldValorConsulta.getText();
            
        }else if(jComboBoxCampoConsulta.getSelectedIndex() == 2){
            return TratamentoComparaData();
        }
    
        return C.RecuperarTodos(parametros);
    }
    
    private void buscarCredenciamento(){
                       
        JSONArray dados = this.parametrosdeconsulta();    // CHAMA A FUNÇÃO PARA VERIFICAR OS PARAMETROS ESCOLHIDOS
        
        //JOptionPane.showMessageDialog(null, dados);
        DefaultTableModel modelo = (DefaultTableModel) jTableCredenciamentos.getModel();
        while (jTableCredenciamentos.getModel().getRowCount() > 0) {             // REMOVE POSSIVEIS ITENS NA TABELA
            modelo.removeRow(0);
        }
        //System.out.println(dados.size());
        
        if(dados != null){
            Iterator i = dados.iterator();

            while (i.hasNext()) {
                JSONObject jsonObj = (JSONObject) i.next();
                Object[] tableData = new Object[]{jsonObj.get("id"), jsonObj.get("id"), jsonObj.get("descricao"),
                    jsonObj.get("pessoa"), jsonRetorno.get("nome"), jsonObj.get("data").toString()};
                System.out.println(Arrays.toString(tableData));
                if (!tableData[0].equals("-1")) {
                    modelo.addRow(tableData);
                }
            }
            jTableCredenciamentos.setModel(modelo);
            if (jTableCredenciamentos.getRowCount() > 0) {
                jTableCredenciamentos.setRowSelectionInterval(0, 0);
            }
        }
    
    }
    
    
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        this.buscarCredenciamento();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jComboBoxCampoConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxCampoConsultaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCampoConsultaKeyPressed

    private void jComboBoxCampoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCampoConsultaActionPerformed
        if(jComboBoxCampoConsulta.getSelectedIndex() == 2){
            jTextFieldValorConsulta.setText("");
            DataCredenciamento.setEnabled(true);
            jTextFieldValorConsulta.setEditable(false);
        }else{
            DataCredenciamento.setDate(null);
            jTextFieldValorConsulta.setEditable(true);
            DataCredenciamento.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxCampoConsultaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCredenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCredenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCredenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCredenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCredenciamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DataCredenciamento;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxCampoConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCredenciamentos;
    private javax.swing.JTextField jTextFieldValorConsulta;
    // End of variables declaration//GEN-END:variables
}
